### ISSUE TITLE
Binary files checked in 

### ISSUE THREAD

**Issue by ashes999** [fictionalreality/StablexuiAndHaxeGuiLearningProjects#1]
The repository contains built files in `bin`. These should be removed.

To remove them, you can create a `.gitignore` file with this text:

```
**/bin/*
```

This will ignore any `bin` directory (regardless of how many parent directories it has) and any files within it.

You will also need to run these commands on the command-line:
- `git rm -rf --cached BasicHaxeCalculator`
- `git rm -rf --cached StableNotepad`

**Comment by anguelesperanza** [comment]
Thank you so much for your help. I've made another repository specifically for the text editor and applied this fix, there as well. I never knew you could do this with GitHub. With your help, the issue has been resolved. I will pay closer attention from now on. Again, thank you.
